name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering from GitHub

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the 'post-it-like-its-hot' repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 PyGithub

      - name: Run the update script
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}  # Built-in GitHub token
        run: python oceanobe/update_readme.py
